#ifndef ERROR_CODES_H
#define ERROR_CODES_H

#include <iostream>

#define FAILED_SET_MOTOR_CMD   0
#define FAILED_ENCODER_RESET   1
#define FAILED_D1_OUT          2
#define FAILED_D2_OUT          3
#define FAILED_CONNECTION      4
#define FAILED_READ_ENCODER_COUNT 5
#define FAILED_READ_ENCODER_SPEED 6
#define FAILED_READ_FEEDBACK 7
#define FAILED_READ_FIRMWARE 8
#define WORNG_INDEXING 9
#define FAILED_READ_MOTOR_CURRENT 10
#define FAILED_READ_MOTOR_VOLTAGE 11
#define FAILED_READ_TEMPERATURE 12
#define NEED_VELOCITY_MODE 13
#define NEED_TORQUE_MODE 14
#define WRONG_SIZE_JOINTSTATE_CMD 15
#define DIFFERENT_MOTOR_MODES 16

void printErrorCode(int code);
#endif